language:
  objective-c
osx_image:
  xcode7.3
xcode_project:
  PlayListPlayer.xcodeproj
xcode_scheme:
  PlayListPlayer
script:
  - carthage update --platform iOS
  - xctool -project PlayListPlayer.xcodeproj -scheme PlayListPlayer clean build test -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
