language:
  objective-c
osx_image:
  xcode9
xcode_project:
  PlayListPlayer.xcodeproj
xcode_scheme:
  PlayListPlayer
script:
  - carthage bootstrap --platform iOS --no-use-binaries
  - bundle install --path vendor/bundle
  - bundle exec fastlane scan --scheme 'PlayListPlayer'
